langue: python
services:
 - docker
python:
  - "2.7"
install:
  - make deps
script:
  - make test
  - make docker_build
deploy:
  provider: heroku
  app: rocky-beach-56935
  api key: ${HEROKU_API_KEY}
